<?php

/**
 * @file
 * Contains redirect_extra.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function redirect_extra_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the redirect_extra module.
    case 'help.page.redirect_extra':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Optional configuration for the Redirect module.') . '</p>';
      return $output;

    default:
  }
}
