<?php

/**
 * @file
 * Contains redirect_extra.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\redirect_extra\RedirectExtraForm;

/**
 * Implements hook_help().
 */
function redirect_extra_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the redirect_extra module.
    case 'help.page.redirect_extra':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Optional configuration for the Redirect module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Redirect create form.
 */
function redirect_extra_form_redirect_redirect_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\redirect_extra\RedirectExtraForm $redirectExtraForm */
  $redirectExtraForm = \Drupal::service('redirect_extra.form');
  $redirectExtraForm->formAlter($form, $form_state, RedirectExtraForm::OPERATION_CREATE);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Redirect edit form.
 */
function redirect_extra_form_redirect_redirect_edit_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\redirect_extra\RedirectExtraForm $redirectExtraForm */
  $redirectExtraForm = \Drupal::service('redirect_extra.form');
  $redirectExtraForm->formAlter($form, $form_state, RedirectExtraForm::OPERATION_EDIT);
}
